In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [6]:
data = pd.read_csv("telco_join.csv")
data.head(6)

State  VMail Message  Day Mins  Eve Mins  Night Mins  Intl Mins  \
0    KS             25     265.1     197.4       244.7       10.0   
1    OH             26     161.6     195.5       254.4       13.7   
2    NJ              0     243.4     121.2       162.6       12.2   
3    OH              0     299.4      61.9       196.9        6.6   
4    OK              0     166.7     148.3       186.9       10.1   
5    AL              0     223.4     220.6       203.9        6.3   

   CustServ Calls  Day Calls  Day Charge  Eve Calls  ...  Night Calls  \
0               1        110       45.07         99  ...           91   
1               1        123       27.47        103  ...          103   
2               0        114       41.38        110  ...          104   
3               2         71       50.90         88  ...           89   
4               3        113       28.34        122  ...          121   
5               0         98       37.98        101  ...          118   

   Night Charge  Intl Calls  Intl Charge  Area Code     Phone Account Length  \
0         11.01           3         2.70        415  382-4657            128   
1         11.45           3         3.70        415  371-7191            107   
2          7.32           5         3.29        415  358-1921            137   
3          8.86           7         1.78        408  375-9999             84   
4          8.41           3         2.73        415  330-6626             75   
5          9.18           6         1.70        510  391-8027            118   

   Churn  Int'l Plan  VMail Plan  
0      0           0           1  
1      0           0           1  
2      0           0           0  
3      0           1           0  
4      0           1           0  
5      0           1           0  

[6 rows x 21 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
STATUSs = LabelEncoder()
UNITSs = LabelEncoder()
State = LabelEncoder()
Phone = LabelEncoder()

In [9]:
data['State'] = STATUSs.fit_transform(data['State'])

data['Phone'] = STATUSs.fit_transform(data['Phone'])

In [10]:
data.head(10)

State  VMail Message  Day Mins  Eve Mins  Night Mins  Intl Mins  \
0     16             25     265.1     197.4       244.7       10.0   
1     35             26     161.6     195.5       254.4       13.7   
2     31              0     243.4     121.2       162.6       12.2   
3     35              0     299.4      61.9       196.9        6.6   
4     36              0     166.7     148.3       186.9       10.1   
5      1              0     223.4     220.6       203.9        6.3   
6     19             24     218.2     348.5       212.6        7.5   
7     24              0     157.0     103.1       211.8        7.1   
8     18              0     184.5     351.6       215.8        8.7   
9     49             37     258.6     222.0       326.4       11.2   

   CustServ Calls  Day Calls  Day Charge  Eve Calls  ...  Night Calls  \
0               1        110       45.07         99  ...           91   
1               1        123       27.47        103  ...          103   
2               0        114       41.38        110  ...          104   
3               2         71       50.90         88  ...           89   
4               3        113       28.34        122  ...          121   
5               0         98       37.98        101  ...          118   
6               3         88       37.09        108  ...          118   
7               0         79       26.69         94  ...           96   
8               1         97       31.37         80  ...           90   
9               0         84       43.96        111  ...           97   

   Night Charge  Intl Calls  Intl Charge  Area Code  Phone  Account Length  \
0         11.01           3         2.70        415   1926             128   
1         11.45           3         3.70        415   1575             107   
2          7.32           5         3.29        415   1117             137   
3          8.86           7         1.78        408   1707              84   
4          8.41           3         2.73        415    110              75   
5          9.18           6         1.70        510   2253             118   
6          9.57           7         2.03        510   1047             121   
7          9.53           6         1.92        415     80             147   
8          9.71           4         2.35        408    291             117   
9         14.69           5         3.02        415    117             141   

   Churn  Int'l Plan  VMail Plan  
0      0           0           1  
1      0           0           1  
2      0           0           0  
3      0           1           0  
4      0           1           0  
5      0           1           0  
6      0           0           1  
7      0           1           0  
8      0           0           0  
9      0           1           1  

[10 rows x 21 columns]

In [11]:
X=data[['VMail Message', 'Day Mins', 'Eve Mins', 'Night Mins', 'Intl Mins', 'CustServ Calls', 'Area Code', 'Account Length','Day Calls', 'Day Charge', 'Eve Calls', 'Eve Charge', 'Night Calls', 'Night Charge', 'Intl Calls', 'Intl Charge', 'VMail Plan' ]]
y=data.Churn 

In [12]:
# Scale the data to be between -1 and 1
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=scaler.fit_transform(X)


C:\Users\ericksen\Anaconda2anacon\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\ericksen\Anaconda2anacon\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [13]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit_transform(X)

array([[ 1.87675378e+00, -5.93781894e-01, -7.39233118e-01, ...,
         4.69355946e-04, -1.50669128e-04,  1.84054887e-04],
       [-4.54959894e-01, -2.49664510e-01,  1.30015197e+00, ...,
        -6.06734594e-04, -3.76579207e-04, -1.93139438e-04],
       [-1.50352582e+00, -8.01160552e-01, -2.68536256e+00, ...,
        -8.98352564e-04,  3.62592297e-04,  1.22410578e-04],
       ...,
       [-3.09542513e-01,  2.04216458e+00, -1.34774563e-01, ...,
        -1.45642401e-03, -3.00576180e-04,  2.65878305e-04],
       [ 8.07578993e-01, -3.96968530e-01, -1.47315406e+00, ...,
         1.22554159e-03, -5.62079520e-04,  2.64786343e-04],
       [ 1.22174349e+00,  1.21780511e+00,  2.17781551e-02, ...,
         9.16932012e-04,  2.33293175e-04,  9.63460238e-05]])

In [14]:
covariance=pca.get_covariance()
explained_variance=pca.explained_variance_



In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn import metrics

model_LR= LogisticRegression()

In [17]:
model_LR.fit(X_train,y_train)


C:\Users\ericksen\Anaconda2anacon\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
y_prob = model_LR.predict_proba(X_test)[:,1] # This will give you positive class prediction probabilities  
y_pred = np.where(y_prob > 0.5, 1, 0) # This will threshold the probabilities to give class predictions.
model_LR.score(X_test, y_pred)

1.0

In [19]:
predictions = model_LR.predict(X)


In [20]:
print("Testing Accuracy :", model_LR.score(X_test, y_test))
print("Training Accuracy :", model_LR.score(X_train,y_train))

('Testing Accuracy :', 0.8740629685157422)
('Training Accuracy :', 0.8559639909977494)


In [109]:

# connect predictions with outputs
for i in range(20):
    print(X[i], predictions[i])


(array([ 1.23488274,  1.56676695, -0.07060962,  0.86674322, -0.08500823,
       -0.42793202, -0.52360328,  0.67648946,  0.47664315,  1.56703625,
       -0.05594035, -0.07042665, -0.46549436,  0.86602851, -0.60119509,
       -0.0856905 ,  1.6170861 ]), 0)
(array([ 1.30794844, -0.33373776, -0.10808036,  1.05857074,  1.24048169,
       -0.42793202, -0.52360328,  0.14906505,  1.12450284, -0.33401297,
        0.14486653, -0.10754944,  0.14782467,  1.05938994, -0.60119509,
        1.2411686 ,  1.6170861 ]), 0)
(array([-0.59175986,  1.16830364, -1.57338336, -0.75686906,  0.70312091,
       -1.1882185 , -0.52360328,  0.9025285 ,  0.67598459,  1.168464  ,
        0.49627857, -1.57389963,  0.19893459, -0.75557074,  0.21153386,
        0.69715637, -0.61839626]), 0)
(array([-0.59175986,  2.19659605, -2.74286476, -0.07855114, -1.30302599,
        0.33235445, -0.68883427, -0.42859027, -1.46693591,  2.19675881,
       -0.60815927, -2.7432675 , -0.5677142 , -0.07880574,  1.02426282,
       -1.30640087

In [23]:
print(X[10], predictions[10])

(array([-0.59175986, -0.93051461,  0.54272717,  0.15678365,  0.88224117,
        1.8529274 , -0.52360328, -0.90578379,  1.82219789, -0.93025113,
       -0.85916786,  0.54209937,  0.55670403,  0.15850147,  0.61789834,
        0.88291665, -0.61839626]), 0)


In [113]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [74]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [99]:
gg = pd.DataFrame(predictions)

In [100]:
gg.to_csv('telco_predictions.csv')


In [101]:
gh = pd.read_csv('telco_predictions.csv')


In [129]:

gh.tail()

Unnamed: 0  0
3328        3328  0
3329        3329  0
3330        3330  0
3331        3331  0
3332        3332  0

In [58]:
dv = pd.DataFrame(y_pred)

In [54]:
dv.to_csv('file_name.csv')


In [1]:
dd = pd.read_csv('file_name.csv', index_col=None)
dd.head()

NameError: name 'pd' is not defined

In [73]:
dd[0].value_counts()

0    652
1     15
Name: 0, dtype: int64